### ISSUE TITLE
panic: EOF

### ISSUE THREAD

**Issue by cumulus13** [aditya-K2/gomp#22]
how to corret it :
      
      Could Not Generate the File Map
      Make Sure You Mention the Correct MPD Port in the config file.
      panic: EOF
   
      goroutine 1 [running]:
      main.main()
	      .../gomp/main.go:65 +0x2112
      exit status 2

**Comment by danrees84** [comment]
Same here. Cantata and ncmpcpp connects fine by comparison.

`MUSIC_DIRECTORY: "~/Music/"
  # Your Music Directory (i.e music_directory in mpd.conf)

#ADDITIONAL_PADDING_X : 9
#ADDITIONAL_PADDING_Y : 17
  # Extra padding for the placement of the image
  # |---------------------------------------------------------|
  # |          ADDITIONAL_PADDING_Y                           |
  # |                      |                                  |
  # |                      v                                  |
  # |                      |---------------|                  |
  # |ADDITIONAL_PADDING_X->|               |                  |
  # |                      |     IMAGE     |                  |
  # |                      |               |                  |
  # |                      |---------------|                  |
  # |                                                         |
  # |                                                         |
  # |---------------------------------------------------------|
  #                              ^
  #                              |
  #                      Image Preview Box
  # Note: Padding can be negative or positive
  # PADDING_X on decrementing will move the image to right and PADDING_Y on incrementing will move the image to left
  # similarly PADDING_Y on decrementing will move the image UP and on incrementing will move the image DOWN

#IMAGE_WIDTH_EXTRA_X  : -1.1
#IMAGE_WIDTH_EXTRA_Y  : -3.75
  # Add extra IMAGE_WIDTH to the image so that it fits perfectly in the image preview box
  #
  # |-----------------------------------------------------------|
  # |                      -  IMAGE_WIDTH_EXTRA_Y               |
  # |                      -         |                          |
  # |                      -         v                          |
  # |-----------------------------------------------------------|
  # |                      -                                    |
  # |                      -                                    |
  # | IMAGE_WIDTH_EXTRA_X  -                                    |
  # |          ->          -                                    |
  # |                      -      IMAGE                         |
  # |                      -                                    |
  # |                      -                                    |
  # |                      -                                    |
  # |                      -                                    |
  # |-----------------------------------------------------------|
  # Note: IMAGE_WIDTH_EXTRA_X and IMAGE_WIDTH_EXTRA_Y can be positive or negative

MPD_PORT : "6600"
  # Port on which music player daemon is running


DEFAULT_IMAGE_PATH:   "default.jpg"

GET_COVER_ART_FROM_LAST_FM : "TRUE" # Turn On Getting Album art from lastfm api
LASTFM_API_KEY: "6126aad50e71cc0d86c6929d8c695a3a"
LASTFM_API_SECRET: "02d1e8b13fffd3d2d35f4d346717a232"
LASTFM_AUTO_CORRECT: 1  # 0 means it is turned off
  # according to lastfm documentation
  # autocorrect[0|1] (Optional) : Transform misspelled artist names into correct artist names, returning the correct version instead.

# Mappings
#
# Mapping works in the following way:
# Function: [ firstMapping, secondMapping, thirdMapping, ...... ]
# for e.g
togglePlayBack : [ "p", "SPACE", "]" ] # using the quotes is neccessary.
  # all the three keys now have the same function.
  # To see Availabe Keys and Functions : https://github.com/aditya-K2/gomp#key-mappings

# Caching
#
# The Covert arts that are extracted from the file or downloaded from lastfm are cached.
# It Is neccessary to define a cache directory to store all the cover arts.
# The Caching works as follows
# 1. Check if there is an embedded cover art if not then 2
# 2. Check if lastfm has album art if not then 3
# 3. Fallback to the default image.
#
#
CACHE_DIR : "~/.config/gomp/cache/" # for e.g "~/.config/gomp/cache/"
  # You will have to manually create this directory.`

**Comment by aditya-K2** [comment]
I am having a tough time pinning down the exact reason for this error, At face value it seems like this is an issue with the [fhs/gompd](github.com/fhs/gompd) library which is used to connect with the music player daemon. If you won't mind can you please drop your `mpd.conf`

**Comment by aditya-K2** [comment]
I think the problem might be the same as mentioned at #33

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @danrees84)
