### ISSUE TITLE
[@somerandomguy24] Border not rendered properly in `ash`

### ISSUE THREAD

**Issue by aditya-K2** [aditya-K2/gomp#51]
There characters surrounding the queue appear to be missing, is there any particular font that is needed to render these? (after further testing, it seems that it is rendered in bash, just not ash (alpine's default shell).
![image](https://user-images.githubusercontent.com/109069892/218827134-48742c02-1422-4402-b900-2b77bfa6a8e0.png)
Other information:
```
mpd-version: 0.23.12
gomp-version: 1.0.0 (2a2579c)
terminal-emulator: alactitty 0.11.0
shell: ash (busybox 1.36.0) | bash (5.2.15)
```

_Originally posted by @somerandomguy24 in https://github.com/aditya-K2/gomp/discussions/50#discussioncomment-4974295_

**Comment by somerandomguy24** [comment]
After some more testing it only occurs in kde plasma, as in sway and a tty it works fine. ~~But I think this is likely not an issue with gomp, since other applications like btop are also acting up.~~ In fact I have figured out the issue myself, and it is **definitely** an issue on my part, you can go ahead and close this issue. Thanks anyways.
